export enum FossologyStatus {
  NOT_STARTED = 'NOT_STARTED',

  UPLOAD_STARTED = 'UPLOAD_STARTED',

  UPLOAD_FINISHED = 'UPLOAD_FINISHED',

  SCAN_STARTED = 'SCAN_STARTED',

  SCAN_FINISHED = 'SCAN_FINISHED',

  FAILURE = 'FAILURE',
}
