package net.regnology.lucy.web.rest.v1;

import net.regnology.lucy.domain.GenericLicenseUrl;
import net.regnology.lucy.repository.GenericLicenseUrlCustomRepository;
import net.regnology.lucy.web.rest.GenericLicenseUrlResource;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Custom REST controller for managing {@link GenericLicenseUrl}
 * where changes are inserted that are different from the base class generated by the JHipster generator.<br>
 * API base path: {@code /api/v1}
 */
@RestController
@RequestMapping("/api/v1")
public class GenericLicenseUrlCustomResource extends GenericLicenseUrlResource {

    public GenericLicenseUrlCustomResource(GenericLicenseUrlCustomRepository genericLicenseUrlRepository) {
        super(genericLicenseUrlRepository);
    }
}
