package net.regnology.lucy.web.rest.v1;

import net.regnology.lucy.service.UserCustomService;
import net.regnology.lucy.service.dto.UserDTO;
import net.regnology.lucy.web.rest.PublicUserResource;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Custom REST controller for managing {@link UserDTO}
 * where changes are inserted that are different from the base class generated by the JHipster generator.<br>
 * API base path: {@code /api/v1}
 */
@RestController
@RequestMapping("/api/v1")
public class PublicUserCustomResource extends PublicUserResource {

    public PublicUserCustomResource(UserCustomService userService) {
        super(userService);
    }
}
